let webApp=require('./webapp.js');
const fs=require('fs');
let getFileData=require('./lib/utils.js').getFileData;
let getMIMEType=require('./lib/utils.js').getMIMEType;
let app=webApp.create();
let requestFileHandler=(req,res)=>{
  let fileName=`./public${req.url}`;
  let fileData=getFileData(fs,fileName);
  res.setHeader('Content-Type',getMIMEType(req.url));
  res.write(fileData);
  res.end();
};
app.get('/',(req,res)=>res.redirect('/login.html'));
app.get('/login.html',requestFileHandler);
app.get('/addTodo.html',requestFileHandler);
app.get('/editTodo.html',requestFileHandler);
app.get('/editTodoItem.html',requestFileHandler);
app.get('/homepage.html',requestFileHandler);
app.get('/viewTodo.html',requestFileHandler);
module.exports=app;
